[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Changelog = "5217a498-cd5d-4ec6-b8c2-9b85a09b6e3e"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
KernelInterpolation = "95686e15-3c94-4443-8f08-76d06d509f7b"
OrdinaryDiffEqLowStorageRK = "b0944070-b475-4768-8dec-fb6eb410534d"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"
TrixiBottomTopography = "86af9953-43df-404b-8eaa-d20d82623a82"
TrixiShallowWater = "804cb1fc-5b08-4398-a671-a789bfe091b3"

[sources.TrixiBottomTopography]
path = ".."

[compat]
CairoMakie = "0.13, 0.15"
Changelog = "1.1"
Documenter = "1.3"
HiGHS = "1.0"
JuMP = "1.0"
KernelInterpolation = "0.3.5"
OrdinaryDiffEqLowStorageRK = "1.3"
Trixi = "0.12, 0.13, 0.14"
TrixiShallowWater = "0.2"
